### ISSUE TITLE
nrepl not found

### ISSUE THREAD

**Issue by gunther-bachmann** [clojure-emacs/clomacs#1]
First of all, 
THANK YOU.
This integration is exactly I was looking for. Great job. Keep up the good work :-)

I had the problem that the nrepl was started correctly but was not found by "clomacs" ("NO repl buffer found - error").

It turned out that the nrepl-connection-list is correctly filled. So the only thing I had to do was to prevent clomacs-defun (line 259) to set the nrepl-connection-list anew. 

The setup I use is:
emacs 24.4
mac os x 10.8
cider 20150604.1532
cider-nrepl  [cider/cider-nrepl "0.9.0-SNAPSHOT"]
nrepl [org.clojure/tools.nrepl "0.2.10"];; actually 0.2.6 is loaded by lein, but that's a different story
java 1.8.0_40

**Comment by kostafey** [comment]
Thank you for your attempt to use clomacs :).

I've fixed the problem, but please be informed that this use case

``` lisp
(clomacs-defun get-property System/getProperty)
(message (get-property "java.version"))
```

is just a demo. The main idea is to write elisp+clojure extensions (e.g. https://github.com/kostafey/ejc-sql). So, all your functions created via `clomacs-defun` should have `:lib-name` parameter to find the exactly your extension repl (it is possible to run your custom clojure project repl and elisp+clojure extension repl at the same time without any mess).
