### ISSUE TITLE
cdr: Wrong type argument: arrayp, ("clojure-test")

### ISSUE THREAD

**Issue by ebpa** [clojure-emacs/clomacs#14]
The issue is on line https://github.com/clojure-emacs/clomacs/blob/0b2df9131a3ee02ae72b5ee170cb443439787e11/src/elisp/clomacs.el#L73

`split-string` returns a list which returns a list of strings rather than a string.  I'm not sure what the intent was in 0b2df9131a3ee02ae72b5ee170cb443439787e11 otherwise I would have included that in a PR.

Thanks!

**Comment by kostafey** [comment]
Thank you. Looks fixed in https://github.com/clojure-emacs/clomacs/commit/047fc3c282c0edb198982987fc816c89313e367c. Could you check it, please?

**Comment by ebpa** [comment]
That did the trick! (thanks :-D
