### ISSUE TITLE
Error: Symbol’s function definition is void: clomacs-doc

### ISSUE THREAD

**Issue by ghost** [clojure-emacs/clomacs#6]
When I tried to install ~clomacs~ using ~mepla~. I got this error message.

```
clomacs.el:339:1:Error: Symbol’s function definition is void: clomacs-doc
```

I cloned this clomacs repo, and revert back to this commit: 6d4eb7a3ba5bc3674c851a8988fa14594952b744 . I can load the lisp
~clomacs.el~. Because some one here https://github.com/kostafey/ejc-sql/issues/11#issuecomment-215473710 indicted that he install successfully that time.

Because I don't have too much knowledge about ~clojure~. I can't really send a pull request.
Can you verify this?

**Comment by kostafey** [comment]
Ok, I think last commit fixed it.

**Comment by ghost** [comment]
Thanks, works now.
