### ISSUE TITLE
Warning msg when installing in spacemacs and the dependent package (ejc-sql) fails to install

### ISSUE THREAD

**Issue by tutysara** [clojure-emacs/clomacs#8]
I see this warning message when installing ejc-sql.
`clomacs.el:353:1:Warning: the function `clomacs--doc' is not known to be defined.`
as a result of which ejc-sql fails to install. Is this something that should be fixed in clomacs?

**Comment by kostafey** [comment]
What kind of spacemacs version do you use? Full or basic?

**Comment by kostafey** [comment]
I've succesfully tested clomacs with spacemacs. @tutysara, could you check please, is it possible to run it now?

**Comment by tutysara** [comment]
Yes, I can run it, thank you.
